<% require 'uri' %>
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  <% if ENV['DATABASE_URL'] %>
  url: <%= ENV["DATABASE_URL"] %>
  host: <%= URI.parse(ENV["DATABASE_URL"]).host %>
  port: <%= URI.parse(ENV["DATABASE_URL"]).port || 5432 %>
  <% else %>
  database: jombo_api_development
  host: localhost
  username: postgres
  password: password
  port: 5432
  <% end %>

test:
  <<: *default
  database: jombo_api_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  <% if ENV['DATABASE_URL'] %>
  host: <%= URI.parse(ENV["DATABASE_URL"]).host %>
  port: <%= URI.parse(ENV["DATABASE_URL"]).port || 5432 %>
  <% end %>
